new dotfiles, based on holman <3

diff --git a/bin/git-nuke b/bin/git-nuke
--- a/bin/git-nuke
+++ b/bin/git-nuke
@@ -1,12 +1,27 @@
-#!/bin/sh
+#!/bin/bash
+set -o errexit
+ 
+# Author: David Underhill
+# Script to permanently delete files/folders from your git repository.  To use 
+# it, cd to your repository's root and then run the script with a list of paths
+# you want to delete, e.g., git-nuke src/file.js node_modules some_other_path
 #
-# Nukes a branch locally and on the origin remote.
+#  retrieved from: http://dound.com/2009/04/git-forever-remove-files-or-folders-from-history/
 #
-# $1 - Branch name.
-#
-# Examples
-#
-#   git nuke add-git-nuke
-
-git branch -D $1
-git push origin :$1
+ 
+if [ $# -eq 0 ]; then
+    exit 0are still
+fi
+ 
+# make sure we're at the root of git repo
+if [ ! -d .git ]; then
+    echo "Error: must run this script from the root of a git repository"
+    exit 1
+fi
+ 
+# remove all paths passed as arguments from the history of the repo
+files=$@
+git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch $files" HEAD
+ 
+# remove the temporary history git-filter-branch otherwise leaves behind for a long time
+rm -rf .git/refs/original/ && git reflog expire --all &&  git gc --aggressive --prune
